name: immortalwrt-x86-64-build

on:
  workflow_dispatch:
    inputs:
      luci_version:
        description: "选择 luci 版本"
        required: false
        default: "25.12.0-rc1"
        type: choice
        options:
          - 25.12.0-rc1
      custom_router_ip:
        description: "路由器 LAN 口管理地址 (例如: 192.168.100.1)"
        required: true
        default: "192.168.100.1"
      profile:
        description: '固件分区大小 单位(MB)'
        required: true
        default: '1024'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      TZ: Asia/Shanghai # 优化：设置时区，让日志时间符合本地习惯
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/x86-64/build25.sh

      - name: Build ImmortalWrt-x86-64-efi 25.12.x
        run: |
          echo "🚀 开始构建固件，分区大小: ${{ inputs.profile }}MB"
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
            -v "${{ github.workspace }}/x86-64/imm25.config:/home/build/immortalwrt/.config" \
            -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
            -v "${{ github.workspace }}/x86-64/build25.sh:/home/build/immortalwrt/build.sh" \
            -e PROFILE="${{ inputs.profile }}" \
            -e CUSTOM_ROUTER_IP="${{ inputs.custom_router_ip }}" \
            immortalwrt/imagebuilder:x86-64-openwrt-${{ inputs.luci_version }} /bin/bash /home/build/immortalwrt/build.sh
          
      - name: Create release info
        run: |
          cat > ${{ github.workspace }}/router-info.md <<EOF
          ## 📡 路由器后台信息
          <a href="https://yishijie.gitlab.io/ziyuan">
            <img src="https://img.shields.io/badge/若下载慢可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
          </a>
          
          - 🏠 **后台地址**: \`${{ inputs.custom_router_ip }}\`
          - 👤 **用户名**: \`root\`
          - 🔑 **密码**: \`无\`
          EOF

      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v2.4.1
        with:
          tag_name: Autobuild-x86-64
          body_path: ${{ github.workspace }}/router-info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
